# Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
#
# Theme Elements & Colors for Hyprland.

# Elements
$hypr_border_size = 3
$hypr_gaps_in = 2
$hypr_gaps_out = 3
$hypr_gaps_ws = -20
$hypr_rounding = 6
$groupbar_font_family = Iosevka
$groupbar_font_size = 10

# Colors
$gradient_angle = 45deg
$active_border_col_1 = 0xFF695861
$active_border_col_2 = 0xFF653945
$inactive_border_col_1 = 0xFF082431
$inactive_border_col_2 = 0xFF063549
$active_shadow_col = 0x66000000
$inactive_shadow_col = 0x66000000
$group_border_active_col = 0xFF3C4349
$group_border_inactive_col = 0xFF4C4C53
$group_border_locked_active_col = 0xFF653945
$group_border_locked_inactive_col = 0xFF695861
$groupbar_text_color = 0xFFbcb4b9
