## Colors configuration
[colors]
alpha=1.0
foreground=bcb4b9
background=02131A

## Normal/regular colors (color palette 0-7)
regular0=02131A  # black
regular1=653945  # red
regular2=3C4349  # green
regular3=4C4C53  # yellow
regular4=695861  # blue
regular5=88374A  # magenta
regular6=985965  # cyan
regular7=bcb4b9  # white

## Bright colors (color palette 8-15)
bright0=837d81   # bright black
bright1=653945   # bright red
bright2=3C4349   # bright green
bright3=4C4C53   # bright yellow
bright4=695861   # bright blue
bright5=88374A   # bright magenta
bright6=985965   # bright cyan
bright7=bcb4b9   # bright white
